DEEPSORT:
  REID_CKPT: "deep_sort_pytorch/deep_sort/deep/checkpoint/ckpt.t7"
  MAX_DIST: 0.2
  MIN_CONFIDENCE: 0.85
  NMS_MAX_OVERLAP: 1
  MAX_IOU_DISTANCE: 0.9
  MAX_AGE: 20
  N_INIT: 3
  NN_BUDGET: 100
  
